### ISSUE TITLE
Lack of Zing support

### ISSUE THREAD

**Issue by RainM** [apangin/helfy#4]
Hi,

It's really an issue, just a remark. Feel free to close this issue.
Azul Zing doesn't have internal HotSpot's 'gHotSpotVMStruct*' symbols  which is a base for helfy library. 

```
$ nm /opt/zing/.../libjvm.so | grep gHotSpotVMStruct
$ nm /usr/lib/jvm/java-1.8.0-oracle-1.8.0.151-1jpp.5.el7.x86_64/.../libjvm.so | grep gHotSpotVMStruct
0000000000fe2c58 B gHotSpotVMStructEntryAddressOffset
0000000000fe2c60 B gHotSpotVMStructEntryArrayStride
0000000000fe2c38 B gHotSpotVMStructEntryFieldNameOffset
0000000000fe2c48 B gHotSpotVMStructEntryIsStaticOffset
0000000000fe2c50 B gHotSpotVMStructEntryOffsetOffset
0000000000fe2c30 B gHotSpotVMStructEntryTypeNameOffset
0000000000fe2c40 B gHotSpotVMStructEntryTypeStringOffset
0000000000fa29c0 D gHotSpotVMStructs
```

Therefore, helfy wont work with Azul Zing anyhow.
As I said before, it's not an bug of helfy. Nevertheless, it's better to know about it.

--Sergey

**Comment by apangin** [comment]
Yes, that's right.
The description of this repository says it is HotSpot JVM introspection library.
There are no plans to support other JVMs.
