### ISSUE TITLE
JVM 6 support

### ISSUE THREAD

**Issue by IgorKey** [apangin/helfy#5]
all of tests crash on JVM6. 
Exceptions like this **java.util.NoSuchElementException: No such field: _name**
All of this work only for JVM8+?

**Comment by apangin** [comment]
I would say JDK 7+.

While helfy engine may work on JDK 6, the contents of VMStructs differs too much on JDK 6 vs. 7. To make examples work on both JDKs, we'll need to have two versions of the code. So I simply decided to drop JDK 6 support.

**Comment by fwflunky** [comment]
ХУЙ
