### ISSUE TITLE
mac 

### ISSUE THREAD

**Issue by lunxian8** [apangin/helfy#6]
No such symbol:gHotSpotVMStructs

**Comment by apangin** [comment]
Can you please elaborate on the problem you're seeing?
What OS / Architecture / Java version do you use?
What is the exact command you run?

**Comment by lunxian8** [comment]
macos/jdk1.8.0_301/getSymbol("gHotSpotVMStructs")   

error：No such symbol:gHotSpotVMStructs

code：

  public long getSymbol(String name) {
        long address = Symbols.lookup(name);
        if (address == 0) {
            throw new NoSuchElementException("No such symbol: " + name);
        }
        return getLong(address);
    }

**Comment by lunxian8** [comment]
"Thank you. These codes run without errors on both Windows and Linux systems. What I need to do is:

https://github.com/apangin/helfy/blob/master/test/one/helfy/DisableStructs.java"

**Comment by lunxian8** [comment]
<img width="414" alt="image" src="https://github.com/apangin/helfy/assets/27261113/688dd664-2136-4229-9197-2fc0df675ea0">

<img width="1070" alt="image" src="https://github.com/apangin/helfy/assets/27261113/f80ab07e-9ea1-4ed1-9e7e-5f822071fbd8">

**Comment by apangin** [comment]
Thank you for the report. Indeed, libjvm.dylib does not export VMStructs symbols on macOS. However, they are still available as private symbols in a shared library. To read those symbols, one will need to implement a mach-O parser to find symbols directly in the dylib.

**Comment by lunxian8** [comment]
Thank you for your response. This area is a knowledge gap for me, and I don't know how to implement it. Hehe

**Comment by apangin** [comment]
I may provide some guidance/consultation if you wish.
I don't plan to implement this myself for free though, since this project (especially, macOS support) is not a priority right now.

**Comment by lunxian8** [comment]
Thank you very much! This is my personal learning project. Currently, macOS is not my development priority. I will focus on completing the code on Linux or Windows. Thank you for your guidance, and I will gradually address macOS support in my subsequent learning. Thanks again!
